# **Name of the Environment**
name: backtestenv  # Name of the Conda environment

# **Channels for Download**
channels:
  - conda-forge  # Channel "conda-forge" with updated and widely supported packages.
  - defaults  # Default Conda channel.

# **Dependencies of the Environment**
dependencies:
  # **Python Version**
  - python=3.12.8  # Specific Python version (3.12.8) for compatibility with other libraries.

  # **Data Analysis and Numerical Calculations Libraries**
  - pandas=2.2.3  # Library for manipulating structured data (DataFrames).
  - numpy=1.26.4  # Library for numerical operations with multi-dimensional arrays.

  # **Financial Data Access**
  - yfinance=0.2.28  # Library for accessing financial market data via Yahoo Finance.

  # **Advanced Data Storage Libraries**
  - pyarrow=17.0.0  # Support for reading and writing Parquet and Arrow formats.
  - tables=3.9.2  # Support for the HDF5 file format, useful for large datasets.

  # **Data Visualization Libraries**
  - matplotlib=3.9.2  # Library for creating graphs and data visualization.

  # **Interactive Development Environment**
  - notebook=7.2.2  # Interactive Jupyter Notebook environment for writing and running code.

  # **Automated Testing Framework**
  - pytest=7.4.4  # Library for creating automated unit tests.

  # **Environment Variable Loading**
  - python-dotenv=1.0.1  # Library for loading environment variables from `.env` files.

  # **Pip Installer Support**
  - pip  # Installation of `pip` to manage packages not available directly via `conda`.

  # **Pip-installed Dependencies**
  - pip:
      # **MetaTrader 5 API**
      - MetaTrader5==5.0.4738  # Official library for connecting to the MetaTrader 5 platform.
      # **Data Validation and Model Definition**
      - pydantic==2.12.0  # Library for data validation and definition of models based on Python.